### PR TITLE
[WIP] - Improve display errors 

### PR DESCRIPTION
**Pull request by tzilist**
This PR is very much a WIP. Currently, we need to watch the error outputs from webpack and bsb while developing. This PR attempts to work on issue #3 .

Currently, we spawn a process for `bsb -make-work -w`, `webpack-dev-server -w` and `berror`. Currently, `berror` seems like a pain to use so this may need to change. We then keep track of the status of webpack and bsb compilation errors/successes and log those to the console.

Each time a file is saved, the terminal is updated in real time to reflect the current status of each compiler.

Here are a few screenshots of what this currently looks like in the terminal.

screenshot from 2017-06-10 18-34-18
screenshot from 2017-06-10 18-34-43
screenshot from 2017-06-10 18-35-08
screenshot from 2017-06-10 18-35-29

Keep in mind this relies heavily on `berror` currently which very much is still in beta.

### CODE REVIEW

**Comment by knowbody** [comment]
This is great! I'm wondering if we could also be showing these errors in the browser, while in DEV mode?

**Comment by tzilist** [comment]
We certainly could. webpack-dev-server does allow for an overlay and I can work on that this week. I figured this would be nice so you don't have to run everything in 2 different terminal sessions.

**Comment by tzilist** [comment]
Added a few more things:

1. Status now can be `Error`, `Compiling`, or `Completed` under BSB and Webpack statuses in the CLI.

If there is an error, it will put it under it's respective compiler.

2. Webpack errors now show as an overlay in the browser.

If anyone feels like it, test it out and let's see how people feel about it!

**Comment by knowbody** [comment]
@tzilist this is amazing! 

the repo changed a bit since last time, do you mind syncing with master please

**Comment by tzilist** [comment]
Ok, updated!

Process now exits on webpack errors and decides whether to use `yarn` or `npm` to execute the start up processes.

**Comment by knowbody** [comment]
Again this is great! Thank you for the PR!

**Comment by knowbody** [comment]
@tzilist I released the version (v0.2.1) with the error display, but I'm not sure it works properly. It doesn't seem to update JS files, and I can't see any errors being displayed in the browser. Do you mind having a look into it please?

**Comment by tzilist** [comment]
On it!

**Comment by tzilist** [comment]
@knowbody So, I just tested this out on a different machine and it seems to be working properly. Can you maybe upload your project so I can take a look? Also, we should probably make sure the users have berror installed as this heavily relies on it. Maybe we can add a link to install `reason-cli` to the package.json?

**Comment by knowbody** [comment]
I think we could do it as a devDependency

**Pull request merged**
