### PR TITLE
Add Service Worker and CSS Modules

### PR DESCRIPTION
**Pull request by tzilist**
This PR will allow users to use CSS Modules and Service Workers right out of the box from CRRA.

To use css in your reason file, you would do one of two things

at the top of your reason file you can type:

```
open Utils

requireCSS "src/app.css"
```

which compiles to

```js
require('src/app.css')
```

The other option is to type

```
let styles = requireCSSModule "src/app.css"
```

This will compile into
```js
const style = require('src/app.css')
```

This particular function must be used with caution but currently works. I can now type something like
```jsx
<div className=style##headerClass > ... </div>
```

Users can also import files (like `.png` or `.svg` with `requireAssetURI`. 

```
<img src=(requireAssetURI "src/logo.svg") />
```

This also adds a service worker, css extraction, among other things, when run in prod. A small script has been added to have express serve from `8080` to test if your build is working as well.

Thanks to @jsdf (https://github.com/jsdf) for giving me the idea for a few of these things!

### CODE REVIEW

**Comment by knowbody** [comment]
@tzilist this is a great PR! Thank you!

However before merging I'd like to discuss a few things. My idea behind CRRA is to have a very minimal config. I don't want it to be the same story as we had with React, where beginners were overwhelmed with the configs.

What do you think about moving a big chunk about CSS modules to the guides? And explaining how they can be added. Or maybe making it even more abstract and explaining how you can add and use any other library into Reason project?

Also we don't need `express` server as for example for deployment to now.sh I use `pushstate-server` so you could just run `build` and then `pushstate-server public/` and you will get the same thing.

What do you think?

**Comment by tzilist** [comment]
Hey, totally! As a matter of fact, here is what I will do, I will turn off CSS modules by default and talk about the different ways you can add CSS to your website. Are you ok with keeping the webpack configs how they are otherwise? 

As for the express server, consider it deleted!

**Comment by tzilist** [comment]
I am a little concerned that if the overall goal is to keep things simple for beginners, these new webpack configs might be a bit much. Perhaps we should put them in a separate folder and allow the user to specify to use them if they are interested? Not sure what the best way to handle this is.

**Comment by tzilist** [comment]
Ok, so I have made some updates,

Currently, CSS Modules are off by default, so users can continue to do what they were doing before with little change. To turn on modules, one would need to run `MODULES=true npm run dev` or something like that. Not sure if I love that solution, but it works for now. We can actually remove this and just put in the write up I added how to enable css modules. That being said, the webpack configs are significantly more complicated than your original version. Should we leave your config as the default and give them some way to access these other ones if they are more interested in creating a reason PWA?

**Comment by knowbody** [comment]
I'd rather have all this explained in the guides for now, so whoever is interested can set these things themselves. But others can just jump in and write some Reason code.

I have a plan of turning this into a CLI tool so maybe then we can pull this set up into some kind of a flag which will generate exactly what you have?

**Comment by tzilist** [comment]
You got it! I'll add the webpack configs into a gist on github and just reference it in the guide! I'll work on that later today :)

**Comment by knowbody** [comment]
check out #15 before that :) maybe worth waiting tiny bit?

**Comment by tzilist** [comment]
Oh cool, didn't see that. I'll let this one sit for a bit, or maybe work on adding the option to the CLI? Let's see what other people think first :)

**Comment by knowbody** [comment]
@tzilist would you like to create a template for this now that we have different templates?

**Comment by tzilist** [comment]
Sure, I'll work on this PR this weekend! 👍

**Comment by knowbody** [comment]
I'm closing this for now, please feel free to add or work on it further in the new PR

**Pull request closed without merging**
